---
# templates/secret.yaml
{{- if not .Values.slack.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-diff-informer.slackSecretName" . }}
  labels:
    {{- include "k8s-diff-informer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.slack.webhookUrl }}
  webhook-url: {{ .Values.slack.webhookUrl | b64enc | quote }}
  {{- else }}
  webhook-url: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}

---