apiVersion: v2
name: k8s-diff-informer
description: A Helm chart for Kubernetes resource change monitoring with Slack notifications.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - monitoring
  - slack
  - informer
home: https://github.com/MIna-Maher/k8s-diff-informer
sources:
  - https://github.com/MIna-Maher/k8s-diff-informer
maintainers:
  - name: MIna-Maher
    email: m.maher.eng2014@gmail.com